Update Security for Symfony 6.2 deprecation notice
thephpleague/oauth2-server-bundle pull request #116
Opened 2023-01-10 15:59 UTC by mogilvie

Resolve issue #115

2023-01-23 15:58 UTC, aleshaczech approved these changes

2023-03-07 12:50 UTC, X-Coder264 requested changes

2023-03-07 12:50 UTC, X-Coder264 commented on src/Resources/config/services.php
> +use Symfony\Bundle\SecurityBundle\Security;
This is not a proper solution. The bundle currently supports >= Symfony 5.3, but this new class was only introduced in Symfony 6.2 so this PR would actually break the bundle for all apps that are not on Symfony 6.2

2023-03-07 14:45 UTC, RobertMe commented
In addition to the comment of @X-Coder264 this fix would also break when Symfony actually removes the `Security` helper in the component (so with Symfony 7.0). This as the `AuthorizationRequestUserResolvingListener` still uses `Symfony\Component\Security\Core\Security` which will then obviously be gone. To fix the deprecation this class should thus be changed as well. (If this bundle only supported PHP >= 8 I think using a union could have fixed it, but as this bundle supports PHP >= 7.2 a union can't be used. So this needs to conditionally switch between two implementations for which one uses the `Security` helper of the bundle and the other the helper of the component).

2023-03-07 19:50 UTC, mogilvie commented
At which point are you going to consider dropping symfony 5.3 and php 7 with a new backward breaking release?

2023-03-07 20:02 UTC, closed without merging

2023-03-08 14:42 UTC, RobertMe commented
Based on the fact that @mogilvie closed this PR I've created a new PR utilizing my proposed solution: #129